# Generated by Django 4.0.3 on 2022-07-08 08:49

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0006_remove_userproduct_date_uploaded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(null=True, upload_to='product/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('date_uploaded', models.DateTimeField(default=datetime.datetime(2022, 7, 8, 13, 19, 1, 512196))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.userproduct')),
            ],
        ),
    ]
