# Generated by Django 4.0.3 on 2022-07-19 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_uservideo_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 11, 13, 40, 36918)),
        ),
    ]
