# Generated by Django 4.0.3 on 2022-07-22 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_alter_uservideo_date_uploaded_alter_uservideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 21, 44, 33, 469453)),
        ),
    ]
