# Generated by Django 4.0.3 on 2022-08-18 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0030_alter_uservideo_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 9, 44, 25, 86274)),
        ),
    ]
