# Generated by Django 4.0.3 on 2022-07-08 08:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_userproduct_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 12, 53, 21, 882848)),
        ),
        migrations.AddField(
            model_name='userproduct',
            name='video',
            field=models.FileField(null=True, upload_to='product/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
