# Generated by Django 4.0.3 on 2022-08-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_userproduct_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproduct',
            old_name='mani',
            new_name='author',
        ),
    ]
