# Generated by Django 4.0.3 on 2022-07-19 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_uservoice_delete_uservideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoice',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 12, 1, 20, 459901)),
        ),
    ]
