# Generated by Django 4.0.3 on 2022-07-22 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_alter_uservoice_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoice',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 21, 47, 37, 353155)),
        ),
    ]
