# Generated by Django 4.0.3 on 2022-06-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
        ('product', '0003_rename_image_userproduct_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='categories',
            field=models.ManyToManyField(blank=True, to='cat.usercat'),
        ),
    ]
