# Generated by Django 4.0.3 on 2022-07-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_userproduct_date_uploaded_userproduct_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproduct',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='userproduct',
            name='video',
        ),
    ]
