# Generated by Django 4.0.3 on 2022-07-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('product', '0010_alter_userproduct_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='topic.usertopic'),
            preserve_default=False,
        ),
    ]
