# Generated by Django 4.0.3 on 2022-07-21 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_alter_uservoice_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoice',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 10, 49, 11, 21673)),
        ),
    ]
