# Generated by Django 4.0.3 on 2022-08-18 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0010_alter_uservoice_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoice',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 9, 46, 41, 604073)),
        ),
    ]
