# Generated by Django 4.0.3 on 2022-06-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_userproduct_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproduct',
            old_name='image',
            new_name='img',
        ),
    ]
