# Generated by Django 4.0.3 on 2022-07-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_userproduct_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproduct',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='userproduct',
            old_name='is_there',
            new_name='exist',
        ),
    ]
