# Generated by Django 4.0.3 on 2022-07-22 17:15

from django.db import migrations, models
import topic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to=topic.models.upload_image_path)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
