# Generated by Django 4.0.3 on 2022-07-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, default='./default_pfp.jpeg', upload_to='profile/'),
        ),
    ]
