# Generated by Django 4.0.3 on 2022-07-19 06:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_userproduct_img'),
        ('videos', '0007_alter_uservideo_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 11, 9, 12, 691180)),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='product.userproduct'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='video',
            field=models.FileField(null=True, upload_to=videos.models.upload_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
